name: "No changing translated files on GitHub"
on:
  pull_request:
    branches:
    - 'main'
    paths:
    - 'curriculum/challenges/**'
    - '!curriculum/challenges/english'

jobs:
  is-invalid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      uses: actions/github-script@v3
      if: startsWith(github.head_ref, 'i18n-sync-learn-') == false
      with:
        script: |
          throw "You appear to be translating files directly on GitHub. Please use Crowdin instead."
